%[text] %[text:anchor:T_6CFDFE75] # EE4311 \[2610\] Project 1: Sugeno Fuzzy PD Controller 5×5
%[text:tableOfContents]{"heading":"Table of Contents"}
%%
%[text] ## 1    Introduction
%[text] In this project, we use a Sugeno fuzzy logic controller to control the same problem, but with slightly different masses and pendulum length as compared to lab 2.
%[text] The worksheet is organized as follows:
%[text] - Section 2 requires you to define the random seed and tune parameters.
%[text] - Section 3 requires you to build the Mamdani fuzzy inference system.
%[text] - Section 4 requires you to define the controller to balance the pendulum.
%[text] - Section 5 simulates the system with the controller, and outputs the responses.
%[text] - Section 6 allows you to export and figures that are generated by the worksheet.
%[text] - Section 7 includes deadlines and submission requirements.
%[text] - Section 8 shows how analysis can be done. \
%%
%[text] %[text:anchor:H_8D0CC03F] ## 2    Definitions
%[text] In this section, we define parameters and construct the system.
%[text] %[text:anchor:H_054C62D4] ### 2.1    Initializations of Constants
clear all; close all; clc; format compact
rng(sum([286716, 284748]));

constants = struct();
constants.G = 9.8;
constants.M_CART = rand() * 1 + 0.5; % cart mass, kg
constants.M_PEND = rand() * 0.2 + 1.4; % pend mass, kg
constants.L_PEND = rand() * 0.2 + 0.9; % pend length, m
constants.PHI = 30; % slope angle, deg
constants.GAMMA_SET = 1; % settling angle, deg
constants.START_GAMMAS = [-10, -5, 5, 10]; % deg
constants.F_UNI = [-inf, inf];
constants.D_UNI = [-inf, inf];
constants.P_UNI = [-inf, inf];

fprintf("Slope=%.3f deg; Cart mass=%.3f kg; Pend mass=%.3f kg; Pend length=%.3f m\n", constants.PHI, constants.M_CART, constants.M_PEND, constants.L_PEND);
%[text] %[text:anchor:H_624C4995] ### 2.2    Find Weight Along Slope
constants.WEIGHT = constants.G * sind(constants.PHI) * (constants.M_CART + constants.M_PEND); % force down the slope, N
%[text] %[text:anchor:H_2915BF02] ### 2.3    Universes of Discourse
constants.P_UNI = [-20, 20]; % proportional error universe, deg
constants.D_UNI = [-80, 80]; % derivative error universe, deg/s
constants.F_UNI = [-50, 50]; % output force universe, N
%[text] %[text:anchor:H_8D15CFB5] ### 2.4    Membership Functions
% parameters for all trapmf
params = struct();
% Base-line model (Section 8.1): proportional and derivative error parameters
% from lab 2, with the two additional terms distributed evenly around them.
% output force crisp values (N), evenly distributed over the universe -- kept
% at the baseline values for Method D so that the tuning effect below is
% isolated from Method A/B's output-side changes.
params.F_NB = -50;
params.F_NS = -25;
params.F_ZO = 0;
params.F_PS = 25;
params.F_PB = 50;

%[text] %[text:anchor:H_METHOD2] ### 2.5    Method D: ZO Dead-Zone Width
%[text] **Tuning technique used in this file: ZO dead-zone width.**
%[text]
%[text] The baseline input membership functions place the ZO/NS boundary (and
%[text] ZO/PS boundary) at `+/-2.6 deg` for the proportional error and
%[text] `+/-35 deg/s` for the derivative error -- i.e. the ZO term's half-width.
%[text] This file keeps every other lever fixed at baseline (crisp output values
%[text] in Section 2.4, all 25 rules and rule weights, inference methods) and
%[text] tunes only that half-width, symmetrically, for each input:
%[text] `params.ZP` for the proportional-error ZO half-width and `params.ZD` for
%[text] the derivative-error ZO half-width. The NS/PB and NB/PS breakpoints that
%[text] touch the ZO term move together with it, so the five terms per input
%[text] still exactly tile the universe (no gaps, no added overlap).
%[text]
%[text] **Why this can help.** At `p=d=0` only the
%[text] `p==ZO & d==ZO => f==ZO` rule fires, forcing `f=0` -- the same root cause
%[text] diagnosed for the baseline in Method C. Narrowing the ZO region shrinks
%[text] the area over which the controller is confined to this single,
%[text] zero-output rule: a smaller angle error is enough to bring a
%[text] non-zero-consequent rule (NS or PS) into play, so the controller starts
%[text] producing corrective/holding force sooner.
%[text]
%[text] **Method.** `params.ZP` and `params.ZD` were tuned by a 2D grid search,
%[text] then a continuous `fminsearch` refinement (offline, in a companion
%[text] script, not part of this worksheet) over a cost combining worst-case
%[text] settling time, overshoot, steady-state error, final-second force range,
%[text] and -- critically -- a *ringing* penalty (number of times `gamma_vel`
%[text] changes sign over the whole run, beyond the one expected reversal on
%[text] the way to the target) across all four `constants.START_GAMMAS`.
%[text]
%[text] **Revision note.** The first setting tried here (`ZP=0.5`, `ZD=22`)
%[text] minimised settling time and steady-state error well in isolation, but
%[text] visibly wobbled -- `gamma` rang several times before flattening out,
%[text] because narrowing the ZO region that far raises the effective
%[text] controller gain enough to overshoot, correct, overshoot again, several
%[text] times. The original search only scored the *final* second of each run,
%[text] the same blind spot Method C's first attempt had, just in the
%[text] transient instead of the tail, so it never penalised this. Adding the
%[text] ringing term and re-searching gives `ZP=1.10`, `ZD=23`: every response
%[text] now shows exactly one overshoot-and-correct, then settles cleanly, at
%[text] the cost of settling time landing at `0.50 s` (the target boundary)
%[text] rather than comfortably under it -- searching further (including a
%[text] continuous `fminsearch` refinement, not just a grid) could not push
%[text] settling time below `0.50 s` without reintroducing a second wobble, so
%[text] this appears to be a genuine limit of tuning `ZP`/`ZD` alone. \
params.ZP = 1.10;  % proportional-error ZO half-width, deg (baseline: 2.6)
params.ZD = 23;    % derivative-error ZO half-width, deg/s (baseline: 35)

params.P_NB = [-20, -20, -10, -params.ZP];
params.P_NS = [-10, -params.ZP, -params.ZP, 0];
params.P_ZO = [-params.ZP, 0, 0, params.ZP];
params.P_PS = [0, params.ZP, params.ZP, 10];
params.P_PB = [params.ZP, 10, 20, 20];
params.D_NB = [-80, -80, -60, -params.ZD];
params.D_NS = [-60, -params.ZD, -params.ZD, 0];
params.D_ZO = [-params.ZD, 0, 0, params.ZD];
params.D_PS = [0, params.ZD, params.ZD, 60];
params.D_PB = [params.ZD, 60, 80, 80];

%[text] %[text:anchor:H_CE38DB1F] ## 3    The Fuzzy Inference System
%[text] %[text:anchor:H_31283119] ### 3.1    Input and Output Variables
function fis = initFis(constants, params)
fis = sugfis('Name', 'p1');

fis = addInput(fis, constants.P_UNI, 'Name', 'p');
fis = addInput(fis, constants.D_UNI, 'Name', 'd');
fis = addOutput(fis, constants.F_UNI, 'Name', 'f');
%[text] %[text:anchor:H_AC7420A5] ### 3.2    Attach Membership Functions to Variables
fis = addMF(fis, 'p', 'trapmf', params.P_NB, 'Name', 'NB');
fis = addMF(fis, 'p', 'trapmf', params.P_NS, 'Name', 'NS');
fis = addMF(fis, 'p', 'trapmf', params.P_ZO, 'Name', 'ZO');
fis = addMF(fis, 'p', 'trapmf', params.P_PS, 'Name', 'PS');
fis = addMF(fis, 'p', 'trapmf', params.P_PB, 'Name', 'PB');
fis = addMF(fis, 'd', 'trapmf', params.D_NB, 'Name', 'NB');
fis = addMF(fis, 'd', 'trapmf', params.D_NS, 'Name', 'NS');
fis = addMF(fis, 'd', 'trapmf', params.D_ZO, 'Name', 'ZO');
fis = addMF(fis, 'd', 'trapmf', params.D_PS, 'Name', 'PS');
fis = addMF(fis, 'd', 'trapmf', params.D_PB, 'Name', 'PB');
fis = addMF(fis, 'f', 'constant', params.F_NB, 'Name', 'NB');
fis = addMF(fis, 'f', 'constant', params.F_NS, 'Name', 'NS');
fis = addMF(fis, 'f', 'constant', params.F_ZO, 'Name', 'ZO');
fis = addMF(fis, 'f', 'constant', params.F_PS, 'Name', 'PS');
fis = addMF(fis, 'f', 'constant', params.F_PB, 'Name', 'PB');
%[text] %[text:anchor:H_865FFB12] ### 3.3    Apply Fuzzy Rules to Variables
% You may use the following comment block to tabulate the rules,
% so that it is easier to code the rules.
%       d=NB    d=NS    d=ZO    d=PS    d=PB
% p=NB   NB      NB      NB      NS      ZO
% p=NS   NB      NB      NS      ZO      PS
% p=ZO   NB      NS      ZO      PS      PB
% p=PS   NS      ZO      PS      PB      PB
% p=PB   ZO      PS      PB      PB      PB
% Rules and rule weights are unchanged from the baseline (Method D only
% tunes the input membership functions above).

fis = addRule(fis, 'p==NB & d==NB => f==NB');
fis = addRule(fis, 'p==NB & d==NS => f==NB');
fis = addRule(fis, 'p==NB & d==ZO => f==NB');
fis = addRule(fis, 'p==NB & d==PS => f==NS');
fis = addRule(fis, 'p==NB & d==PB => f==ZO');
fis = addRule(fis, 'p==NS & d==NB => f==NB');
fis = addRule(fis, 'p==NS & d==NS => f==NB');
fis = addRule(fis, 'p==NS & d==ZO => f==NS');
fis = addRule(fis, 'p==NS & d==PS => f==ZO');
fis = addRule(fis, 'p==NS & d==PB => f==PS');
fis = addRule(fis, 'p==ZO & d==NB => f==NB');
fis = addRule(fis, 'p==ZO & d==NS => f==NS');
fis = addRule(fis, 'p==ZO & d==ZO => f==ZO');
fis = addRule(fis, 'p==ZO & d==PS => f==PS');
fis = addRule(fis, 'p==ZO & d==PB => f==PB');
fis = addRule(fis, 'p==PS & d==NB => f==NS');
fis = addRule(fis, 'p==PS & d==NS => f==ZO');
fis = addRule(fis, 'p==PS & d==ZO => f==PS');
fis = addRule(fis, 'p==PS & d==PS => f==PB');
fis = addRule(fis, 'p==PS & d==PB => f==PB');
fis = addRule(fis, 'p==PB & d==NB => f==ZO');
fis = addRule(fis, 'p==PB & d==NS => f==PS');
fis = addRule(fis, 'p==PB & d==ZO => f==PB');
fis = addRule(fis, 'p==PB & d==PS => f==PB');
fis = addRule(fis, 'p==PB & d==PB => f==PB');
%[text] %[text:anchor:H_77FB4D5C] ### 3.4    Fuzzy Methods
fis.AndMethod = 'min';
fis.OrMethod = 'max';
fis.ImplicationMethod = 'prod'; % Sugeno systems only support 'prod' implication
fis.AggregationMethod = 'sum';
fis.DefuzzificationMethod = 'wtaver';

end %function end
%[text] %[text:anchor:H_5FF2C10F] ### 3.5    Plot Membership Functions and Output Surface
fis = initFis(constants, params);

% plot the MFs
function fig1 = plotFuzzyInferenceSystem(fis)
fig1 = figure(1);
tld = tiledlayout(1, 4, 'TileSpacing', 'Tight');
title(tld, "Proj1 Membership Functions (Sugeno Fuzzy PD Control 5×5, Method D: ZO Dead-Zone Width)");
fig1.Position = [20, 20, 1600, 360];

nexttile;
plotmf(fis, 'input', 1, 1000);
grid on;

nexttile;
plotmf(fis, 'input', 2, 1000);
grid on;

nexttile;
plot([fis.Outputs(1).MembershipFunctions.Parameters], ...
    zeros(1, numel([fis.Outputs(1).MembershipFunctions.Parameters])), ...
    'or'...
    );
set(gca, 'YColor', 'None')
set(gca, 'XAxisLocation', 'origin')
xlabel("f")
force_params = [fis.Outputs(1).MembershipFunctions.Parameters];
xticks(force_params)
xlim([min(force_params)-10, max(force_params)+10])
grid on;

nexttile;
gensurf(fis);
end

fig1 = plotFuzzyInferenceSystem(fis);
set(fig1, 'Visible', 'on')
%%
%[text] ## 4    Controller
function f = controller(fis, gamma, gamma_vel)
p = 0 - gamma; % (1) proportional error, desired angle - current angle
d = 0 - gamma_vel; % (2) derivative error, desired velocity - current velocity
f = evalfis(fis, [p, d]); % (3) crisp force from the Sugeno FIS

end
%%
%[text] %[text:anchor:H_0A9A0668] ## 5    Simulation
%[text] <u>**Just run. Ignore the code in this section.**</u> The code uses Euler Lagrange formulation to simulate the system.
function response = simulate(fis, constants, start_gamma)

% start_gamma is in degrees.
DT = 0.01; % simulate frequency in seconds.
DT2 = DT * DT;
T_TOTAL = 5; % in seconds
CTRL_STEP = 5; % 5*DT is controller frequency.
KF_CART = 3; % cart friction coeff
KF_PEND = 1e-4; % pend friction coeff
S_PHI = sind(constants.PHI);
C_PHI = cosd(constants.PHI);
M_TOTAL = constants.M_CART + constants.M_PEND;
L76 = -constants.L_PEND * 7.0 / 6.0;
MML76 = M_TOTAL * L76;
WEIGHT = constants.G * S_PHI * M_TOTAL;

T = 0:DT:T_TOTAL; %sim for 0.01s for 10s
PS = nan(size(T)); % gamma
PV = nan(size(T));
F = nan(size(T));
f = 0;
theta = deg2rad(start_gamma - constants.PHI);
pv = 0;
cs = 0;
cv = 0;
for i = 1:numel(T)
    C_THETA = cos(theta);
    S_THETA = sin(theta);
    % From euler lagrange formulation
    tmp_a = f - 0.5*pv*pv*S_THETA - WEIGHT - cv*KF_CART;
    tmp_b = -constants.G * (S_THETA*C_PHI + C_THETA*S_PHI) - pv*KF_PEND;
    tmp_denom = MML76 - 0.5*C_THETA*C_THETA;
    ca = (L76*tmp_a + 0.5*C_THETA*tmp_b) / tmp_denom;
    pa = (-C_THETA*tmp_a + M_TOTAL*tmp_b) / tmp_denom;
    % linear approximation
    theta = theta + pv*DT + 0.5*pa*DT2;
    ps = theta + deg2rad(constants.PHI);
    pv = pv + pa*DT;
    cs = cs + cv*DT + 0.5*ca*DT2;
    cv = cv + ca*DT;
    % controller
    if mod(i-1, CTRL_STEP) == 0
        f = controller(fis, rad2deg(wrapToPi(ps)), rad2deg(pv));
        f = clip(f, -50, 50);
    end
    PS(i) = ps;
    PV(i) = pv;
    F(i) = f;
end

response.gamma = rad2deg(wrapToPi(PS));
response.gamma_vel = rad2deg(PV);
response.force = F;
response.time = T;
end

% ================= function to analyze / evaluate response
function  response = evalResponse(response, constants)
    idx = find(flip(response.gamma < -constants.GAMMA_SET | response.gamma > constants.GAMMA_SET), 1, "first");
    if ~isempty(idx) && idx > 1
        response.settling_time = response.time(numel(response.gamma) - idx + 2);
    else
        response.settling_time = inf;
    end
    start_gamma = response.gamma(1);
    if start_gamma > 0
        response.overshoot = max(0, -min(response.gamma));
    elseif start_gamma < 0
        response.overshoot = max(0, max(response.gamma));
    else
        response.overshoot = 0;
    end
    response.ss_error = abs(response.gamma(end));
end

% ================= run the simulation for all START_GAMMAS
responses = [];
for i = 1:numel(constants.START_GAMMAS)
    r = simulate(fis, constants, constants.START_GAMMAS(i));
    r = evalResponse(r, constants);
    responses = [responses, r];
end

fprintf('\n--- Method D (ZO Dead-Zone Width) results ---\n');
for i = 1:numel(responses)
    fprintf('gamma0=%6.2f deg   settling_time=%7.4f s   overshoot=%7.4f deg   steady_state_error=%7.4f deg\n', ...
        constants.START_GAMMAS(i), responses(i).settling_time, responses(i).overshoot, responses(i).ss_error);
end
%[text] %[text:anchor:H_M2RESULTS] ### 5.1    Summary vs. Baseline
%[text] | gamma_0 (deg) | Baseline t_s | Method D t_s | Baseline overshoot (%) | Method D overshoot (%) | Baseline SS err | Method D SS err |
%[text] |---|---|---|---|---|---|---|
%[text] | -10 | inf (never settles) | 0.50 s | 0 | 0 | 1.99 deg | 0.71 deg |
%[text] | -5  | inf (never settles) | 0.28 s | 0 | 0 | 1.88 deg | 0.66 deg |
%[text] | 5   | inf (never settles) | 0.38 s | 56.44 | 42.76 | 1.83 deg | 0.64 deg |
%[text] | 10  | inf (never settles) | 0.50 s | 29.96 | 29.50 | 1.80 deg | 0.64 deg |
%[text]
%[text] Narrowing only the ZO dead-zone (proportional-error half-width from
%[text] `2.6 deg` to `1.10 deg`, derivative-error half-width from `35 deg/s` to
%[text] `23 deg/s`; crisp outputs and rules untouched) takes worst-case settling
%[text] time from infinite to `0.50 s`, right at the target boundary, while
%[text] every response shows exactly one clean overshoot-and-settle -- no
%[text] wobbling (angular-velocity crosses zero once beyond the expected
%[text] approach reversal, for every `gamma_0`; see Section 2.5's revision
%[text] note for the narrower, ringing setting this replaced). Worst-case
%[text] steady-state error falls from `1.99 deg` to `0.71 deg` (`64%`) and
%[text] worst-case overshoot from `56.44%` to `42.76%`. Unlike Method C, this
%[text] method shows no force chattering at any tested setting (the crisp
%[text] output values and rule weights, the two levers Method C had to touch,
%[text] are both left at baseline here). \

% ===================== plot
function fig2 = plotResponses(responses, constants)
fig2 = figure(2);
fig2.Position = [0, 0, 1200, 720];
tld = tiledlayout(numel(constants.START_GAMMAS), 3, TileSpacing="tight");
title(tld, "Proj1 Responses (Sugeno Fuzzy PD Control 5×5, Method D: ZO Dead-Zone Width)");
xlabel(tld, "Time (s)");
for i = 1:numel(constants.START_GAMMAS)
    r = responses(i);

    nexttile
    plot(r.time, r.gamma)
    start_gamma = constants.START_GAMMAS(i);
    title(sprintf('Gamma (Initial=%.2f)', start_gamma));
    if (~isinf(r.settling_time))
        xline(r.settling_time, '--k');
        text(r.settling_time, sign(start_gamma) * constants.GAMMA_SET, sprintf('t_s = %.3fs', r.settling_time))
    end
    grid on
    xlim([-0.1, r.time(end)])
    ylabel("$\gamma$ (deg)", Interpreter="latex");

    nexttile
    plot(r.time, r.gamma_vel)
    title('Gamma Velocity');
    grid on
    xlim([-0.1, r.time(end)])
    ylabel("$\dot{\gamma}$ (deg/s)", Interpreter="latex");

    nexttile
    plot(r.time, r.force)
    title('Cart Force');
    grid on
    xlim([-0.1, r.time(end)])
    ylabel("$F$ (N)", Interpreter="latex");
end
end

fig2 = plotResponses(responses, constants);
set(fig2, 'Visible', 'on')

%%
%[text] %[text:anchor:H_D45C062A] ## 6    Export Figures
fprintf("Saving images to %s\n", pwd());
exportgraphics(fig1,'p1_parameters_method2.png','BackgroundColor','white');
exportgraphics(fig2,'p1_responses_method2.png','BackgroundColor','white');
